### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by kougin** [VictorAlbertos/RxActivityResult#12]
in HolderActivity.onCreate(HolderActivity.java:33)
onResult = request.onResult()

**Comment by VictorAlbertos** [comment]
Hi.

I'm gonna need to stack strace as long as the code you used to perform the intent call.

Thanks!

**Comment by iveyalkin** [comment]
This one might be the same as already described in https://github.com/VictorAlbertos/RxActivityResult/issues/9
