### ISSUE TITLE
What about startActivityForResult

### ISSUE THREAD

**Issue by theGlenn** [VictorAlbertos/RxActivityResult#13]
In #3 you talked about `startIntentSenderForResult` but what an implementation for `startActivityForResult` a lot of api like the Google login for example requires to call it.

**Comment by VictorAlbertos** [comment]
Hi @theGlenn 

`startActivityForResult` is the main feature which RxActivityResult provides :)

```
Intent takePhoto = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
RxActivityResult.on(this)
      .startIntent(takePhoto)
      .subscribe(result -> {})
```

When subscribing, the emitted item is the result. 

You can take a look [here](https://github.com/VictorAlbertos/RxActivityResult/blob/master/rx_activity_result/src/main/java/rx_activity_result/HolderActivity.java#L69) to dig into the implementation.

**Comment by theGlenn** [comment]
Hi @VictorAlbertos,

Ok, I see but on `startActivityForResult(intent, requestCode)` the second argument is the request code how do you pass it? 

ex: `startActivityForResult(signInIntent, RequestCode.GOOGLE_SIGNIN);`

**Comment by VictorAlbertos** [comment]
You don't need to supply ant request code. The request code is [only a flag](https://developers.google.com/identity/sign-in/android/) which RxActivityResult already automatically supplies it. 

So, just pass as argument your `signInIntent` and you are good to go ;)

**Comment by theGlenn** [comment]
Ah yeah off course it make sense since we are in the chain!! Thank you!
