### ISSUE TITLE
Method RxActivityResult.register(this) not exist

### ISSUE THREAD

**Issue by cosic** [VictorAlbertos/RxActivityResult#2]
Seems the library doesn't have static method RxActivityResult.register(...) that mentioned to the README.md

**Comment by VictorAlbertos** [comment]
Hi!

Are you using the new version '0.2'?

compile "com.github.VictorAlbertos:RxActivityResult:0.2"

**Comment by cosic** [comment]
Oh, sorry! I cloned repo yesterday and didn't pay attention that you released new version after that. )
