### ISSUE TITLE
RxActivityResult.on(fragment) not working on DialogFragment

### ISSUE THREAD

**Issue by vekexasia** [VictorAlbertos/RxActivityResult#36]
Hello, i'm usin 4.2.0 since 4.2.1 is not "pullable".

Apparently DialogFragment is not getting any result back when using .on(fragmnet). 

If i change it with .on(getActivity()) everything works fine.

**Comment by VictorAlbertos** [comment]
Do you care to take a look? Thanks

**Comment by VictorAlbertos** [comment]
Feel free to reopen it if you were willing to submit a PR ;)
