### ISSUE TITLE
requestCode parameter not found in Result

### ISSUE THREAD

**Issue by esunilkumare** [VictorAlbertos/RxActivityResult#37]
The Andorid method does have three parameters in the method onActivityResult: requestCode, resultCode and data. 

> onActivityResult(int requestCode, int resultCode, Intent data)

However, the [Result ](https://github.com/VictorAlbertos/RxActivityResult/blob/2.x/rx_activity_result/src/main/java/rx_activity_result2/Result.java)class does not have these parameters

**Comment by maarek** [comment]
PR #38

**Comment by esunilkumare** [comment]
Merged PR #38, with this issue fix. Hence closing the issue.
