### ISSUE TITLE
When windowIsTranslucent is true in theme style, screen will flash once target activity finished.

### ISSUE THREAD

**Issue by FioneraGH** [VictorAlbertos/RxActivityResult#46]
Thanks for the library, its very convenient to be used.
But when windowIsTranslucent is true in theme style, screen will flash once target activity finished. It looks like the HolderActivity cannot handle the transition anim correctly, because when windowIsTranslucent is false, there is no issue.

**Comment by VictorAlbertos** [comment]
Do you care to submit a PR?

**Comment by FioneraGH** [comment]
@VictorAlbertos After that, I try to find the reason, I found it appears only on pre L, perhaps it's not an issue. Now close it :P

**Comment by FioneraGH** [comment]
@VictorAlbertos I found the HolderActivity's  windowIsTranslucent is true. When two translucent activity finish at the same time, transition anim will be broken. Do u hava idea to deal with it?

**Comment by VictorAlbertos** [comment]
No 😅
