### ISSUE TITLE
AndroidX

### ISSUE THREAD

**Issue by JvmName** [VictorAlbertos/RxActivityResult#58]
Hi! I'm migrating our app to AndroidX, and I was wondering:
1. do you have a timeline for migrating to this library to AndroidX?
2. if I submit a PR migrating the lib to AndroidX, what would be the timeline to having it released?

**Comment by VictorAlbertos** [comment]
What changes are required to migrate to `AndroidX`?

> if I submit a PR migrating the lib to AndroidX, what would be the timeline to having it released?

A few days at most.

**Comment by JvmName** [comment]
In general, it's mostly just rewriting the `import` statements to use the `androidx.` classes instead of `android.support.`. 

There's a refactor tool inside Android Studio that ought to do most of the work, and there's a (short) guide [here](https://developer.android.com/jetpack/androidx/migrate)

**Comment by VictorAlbertos** [comment]
Closed via #59
