### ISSUE TITLE
Results taking up to 10 seconds

### ISSUE THREAD

**Issue by FranciscoE-Hudl** [VictorAlbertos/RxActivityResult#6]
I'm using RxPaparazzo in our app, but the adding picture has severe delays on our Samsung devices, north of 10 seconds.

```
return RxActivityResult.on(targetUi.activity())
        .startIntent(intent)
        .map(new Func1<Result<Activity>, Intent>() {
            @Override
            public Intent call(Result<Activity> result) {
                return StartIntent.this.getResponse(result);
            }
        });
```

The map function would take 10 seconds since the Observable was started. Attach sources doesn't work for me so I can't debug further than that.

**Comment by FranciscoE-Hudl** [comment]
I've continues testing it and I've narrowed it down to holder activity taking those seconds between onActivityResult and onDestroy. When finish() is called, it still takes several seconds to be collected.

**Comment by VictorAlbertos** [comment]
Hi @FranciscoE-Hudl.

That's really weird. I've used RxActivityResult with several intents on several devices, and I have never noticed this issue. 

Have you tried to supply another kind of intent which expects a result back? Just to know if this issue is related with the kind of intent, or it is something more general which happens to these devices for another reason.

Thanks.

**Comment by FranciscoE-Hudl** [comment]
I'm running the tests on this branch: 

```
dependencies {
        compile 'com.github.FranciscoE-Hudl:RxActivityResult:-SNAPSHOT'
}
```

Logs:

```
05-20 16:25:07.425 4139-4139/com.my.app D/HolderActivity: Result received: 1463757907434
05-20 16:25:17.435 4139-4139/com.my.app D/HolderActivity: Result forwarded: 1463757917451
```

**Comment by FranciscoE-Hudl** [comment]
The bug happens on both the result from the picture request and the UCrop one.

**Comment by FranciscoE-Hudl** [comment]
The bug doesn't happen on the sample app (!)

**Comment by VictorAlbertos** [comment]
I'm a little lost here. xD

Do you mean that when you run the rxpaparazzo sample app on those same devices the bud does not happen?

**Comment by FranciscoE-Hudl** [comment]
Okay, so I've narrowed it down. 

It's a Samsung 5.1.1 bug for RxPaparazzo: from finish() to onDestroy() there are 10 seconds. Seen on 2 different Samsung devices: S5 and Tab S2.

**Comment by VictorAlbertos** [comment]
If you want we can discuss the issue on [gitter](https://gitter.im/VictorAlbertos/RxActivityResult?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). It will be more productive ;)

**Comment by FranciscoE-Hudl** [comment]
I've tried to reproduce it on the same devices with the sample app and I couldn't, so it's related to my own app :-1:

**Comment by manthan5493** [comment]
did you found any solution on that i am going through same issue
